### PR TITLE
Release/1.1.2

### PR DESCRIPTION
**Pull request by paulboocock**
Bumped Enrich to 2.0.0

### CODE REVIEW

**Review by istreeter — APPROVED** [review]
LGTM!  Thanks @paulboocock 

I spent a bit of time wondering if this should be a patch release, or whether it should be 1.2.0.  But I think you are right - the functionality added by Enrich 2.0.0 does not affect the output of micro.

**Comment by istreeter** [comment]
> Yeah, the only thing I could see that would change is the YAUAA output, but since that was a patch change I didn't think it really warranted a new Minor release here.

The yauaa enrichment is not enabled in micro - nor is any other enrichment.  So definitely does not warrant a new Minor here.

**Comment by istreeter** [comment]
I suggest we delay releasing this until collector 2.3.0 is released - which should be very soon.  Currently we have added no new features, nor fixed any micro bugs, so I don't see a rush to get this released.  Collector 2.3.0 will also contribute no new features for micro - but at least we can then bump all dependencies at the same time.

**Comment by paulboocock** [comment]
Sounds good to me 👍

**Pull request closed without merging**
