### PR TITLE
Return good events in the canonical event format (closes #28)

### LINKED ISSUE #28: Return good events in the canonical event format
The enrichment manager returns events in the form of the [EnrichedEvent defined in the enrich repo](https://github.com/snowplow/enrich/blob/scala_common_enrich/1.1.0/modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/outputs/EnrichedEvent.scala#L38)

We could convert those events into the [canonical Snowplow Event class](https://github.com/snowplow/snowplow-scala-analytics-sdk/blob/2.0.1/src/main/scala/com.snowplowanalytics.snowplow.analytics.scalasdk/Event.scala#L39)

There are a number of benefits:
- The latter is a case class, so circe can auto-generate an encoder. It removes the ugly code where we explicitly create an encoder field-by-field for the EnrichedEvent.
- Timestamps in the EnrichedEvent class are strings in a format suited for loading into a database, but not in ISO8601 format.  For example `2020-07-29 15:06:00.557`.  In the Event class, timestamps are java Instants, so they get serialized by default into ISO8601 format `2020-07-29T15:06:00.557Z`
- Contexts and unstruct events in EnrichedEvent class are json-escaped strings.  So a consumer of the EnrichedEvent needs to do a secondary json decode of these fields.  Whereas contexts and unstruct events in the Event class are stored as SelfDescribingData which gets nicely serialized as a json object.
- More generally, converting all the way to an Event during testing gives some extra assurance that a payload will get processed correctly end-to-end by a full snowplow pipeline.

### PR DESCRIPTION
**Pull request by istreeter**

### CODE REVIEW

**Comment by benjben** [comment]
This is awesone @istreeter !

**Comment by istreeter** [comment]
@benjben Since creating the pull request, I found a bug I need to fix - some values are not getting converted properly, e.g. some nulls are getting converted to `Some(0)` instead of `None`.  Fairly sure I can fix this.

We should also discuss if some of this code belongs in a different repo - I feel it has uses beyond just micro.  For example, I was hoping this event-conversion functionality could be dropped into the analytics sdk repo.  Unfortunately that's difficult because of circular dependencies:

- The event conversion depends on enrich and badrows and the analytics sdk
- Enrich has snowplow-badrows as a dependency
- BadRows has the analaytics sdk as a dependency

Do you have any ideas how to solve this circular puzzle?

**Comment by benjben** [comment]
@istreeter I don't think that this is too much of a problem. Event conversion gets snowplow-badrows and analytics SDK through enrich. When analytics SDK gets updated, we need to update snowplow-badrows, and then enrich, but this is what we do anyway to keep all our libraries/apps versions aligned.

**Comment by istreeter** [comment]
@benjben I tracked down the source of the bug I mentioned above... it's actually in the enrich repo, not here.  I am using the [toPartiallyEnrichedEvent method](https://github.com/snowplow/enrich/blob/master/modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/outputs/EnrichedEvent.scala#L252).  It converts values like this:

```scala
ti_quantity = Option(Integer2int(enrichedEvent.ti_quantity)),
```

The problem is that `Ineger2int` converts null to 0.  So I think we need to change the conversions like this:

```scala
ti_quantity = Option(enrichedEvent.ti_quantity).map(Integer2int),
````

...which will properly return `None` instead of `Some(0)` when the value is missing.

Do you agree, and shall I try to release a patched version of enrich with this change?  I don't think we should release micro until this is fixed.

**Comment by benjben** [comment]
> ti_quantity = Option(enrichedEvent.ti_quantity).map(Integer2int),

Totally agree @istreeter it should be like this !

We are planning to release 1.4.0 soon, @chuwy can we integrate this fix of `Integer2int` in it ?

**Pull request merged**
