### PR TITLE
Release 1.4.0

### PR DESCRIPTION
**Pull request by stanch**

### CODE REVIEW

**Comment by istreeter** [comment]
If you look at the git history, we normally name commits like `(close #129)` not just `(#129)`.  If you care about consistency, you could rebase the branch and rename the commits.  Give me a shout if you want help with that.

Otherwise I think the release looks good, as long as @greg-el is happy with it too.

**Review by greg-el — COMMENTED** [review]
Looks great, I'm a big fan of the ability to pipe out events.

A reservation I have is that `--print` isn't very descriptive of the function it performs. I think this comes from two places:
1. As this release includes the new ability to "print" out events as they are received, there might be confusion as to the purpose of this flag (e.g. do I need this flag just to enable printing events in the first place, as it didn't print anything by default before?)
2. `print` isn't a flag I would associate with modifying the output format of logs

I can't say I know too much about how the users think of the output from micro, so `--print` changing the format of the output to TSV may feel natural for them, but to me something like `--log-tsv-events` or `--tsv-events` (or even just `--tsv` if that seems ok?) would be more understandable.

The only other reservation is changing the default output of micro by enabling event logging by default, but that is probably just being overly cautious (but we never know if someone out there has implemented a [spacebar heater](https://xkcd.com/1172/))

**Comment by stanch** [comment]
> If you look at the git history, we normally name commits like (close #129) not just (#129). If you care about consistency, you could rebase the branch and rename the commits.

That’s because I did not create the corresponding issues, so #129 and #130 are PR numbers. Sorry!

> `--print` changing the format of the output to TSV may feel natural for them

I suspect there is a misunderstanding of what the option does (which I promise will be explained in the announcement and the docs in due time!) It does not _change_ the format at all!
* Micro now always logs events. The purpose of this new feature is to aid debugging. All logs go to STDERR (sic!) and contain various decoration, like `[INFO]` etc. You can control them with `-Dorg.slf4j.simpleLogger.log.EventLog=off` to turn off the event logs specifically, or `-Dorg.slf4j.simpleLogger.defaultLogLevel=off` to turn off _all_ logs. Or you can change the logging format entirely to your liking.
* Outputting TSV is completely independent and is to STDOUT (sic!). If you enable it, you will have both the logs and the TSV. For piping into other tools, which is the main purpose of this feature, it does not matter (or may even help, so that you still see you are receiving events without the need to jump through hoops with `tee` or the like). However if both outputs are undesirable, you can either suppress the logs as above, or simply redirect STDERR to `/dev/null`.

With this in mind, I don’t think `--tsv-events` or `--tsv` are accurate, as they don’t convey that an _additional action_ is happening. However, I can be convinced to change `--print` to `--output-tsv-events` if you prefer.

**Comment by greg-el** [comment]
Ah, I see where my misunderstanding came from. As discussed on slack, `--output-tsv` seems like a decent name.

**Review by greg-el — APPROVED** [review]
LGTM!

**Pull request merged**
